cart/urls.py
from django.urls import path
from . import views
   
app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:prod_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:prod_id>/', views.cart_remove, name='cart_remove'),

]

orders/urls.py
from django.urls import path  
from . import views
   
app_name = 'orders'
   
urlpatterns = [
	path('create/', views.order_create, name='order_create'),
	path('order-created/', views.order_created, name='order_created'),
]

s3palace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('search/', views.search, name='search'),
	path('gallery/', views.gallery, name='gallery'),
	path('<int:id>/<slug:slug>/', views.suit_detail,name='suit_detail'),
	path('suits/<slug:category_slug>/', views.category_list,name='product_list_by_category'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
   
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
   
class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class CartUpdateProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	override = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Suits, Category
from .cart import Cart
from .forms import CartAddProductForm, CartUpdateProductForm
   
@require_POST
def cart_add(request, prod_id):
	cart = Cart(request)
	product = get_object_or_404(Suits, id=prod_id)
	form = CartAddProductForm(request.POST)
	print('This is the cart:',cart)
	print('This is the product from the cart view:', product, product.image.url)

	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
	return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, prod_id):
    cart = Cart(request)
    suit = get_object_or_404(Suits, id=prod_id)
    suit_det = get_object_or_404(Suits, id=prod_id, available=True)
    cart.remove(suit)
    return redirect('cart:cart_detail')

def cart_detail(request, category_slug=None):
    cart = Cart(request)
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
        
    for item in cart:
        item['update_quantity'] = CartAddProductForm(initial={
			'quantity':item['quantity'],
			'override': True})#item_update_form = CartUpdateProductForm()
    print('This is the cart detail:',cart)
    
    context = {
		'category': category,
        'suits':suits,
        'categories': categories,
        'cart': cart
     }
    return render(request, 'cart/cart_detail.html', context) 

cart/templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}

  {% block title %} SD eShop - Your shopping cart {% endblock %}
   
  {% block content %}
<!--//header-->
<div class="breadcrumbs">
  <div class="container">
    <ol class="breadcrumb breadcrumb1 animated wow slideInLeft animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInLeft;">
      <li><a href="{% url 'shop:home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
      <li class="active">Cart</li>
    </ol>
  </div>
</div>
<!---->

  <div class="container">
    <div class="check-out">
      <h2>Your Shopping Cart</h2>
      <table border="0.5" style="text-align:center; margin:auto; spacing: 50px; padding:10px;">
        <thead style="text-align:center; background-color:#333; color:gold;"> 
          <tr style="text-align:center; padding:10px;">
            <th style="text-align:center; padding:10px; color:#e4e008e1;">Item</th>
            <th style="text-align:center; padding:10px; color:#e4e008e1;">Quantity</th>		
            <th style="text-align:center; padding:10px; color:#e4e008e1;">Remove Item</th>
            <th style="text-align:center; padding:10px; color:#e4e008e1;">Unit Price</th>
            <th style="text-align:center; padding:10px; color:#e4e008e1;">Sub Total</th>
          </tr>
        </thead>
        <tbody style="text-align:center;">
          {% for item in cart %} 
            {% with product=item.product %}
              <tr>
                <td class="ring-in">
                  <a href="{{ product.get_absolute_url }}" class="at-in">
                    <img src="{% if product.image %}{{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}" class="img-responsive" alt="">
                  </a>
                  <div class="sed">
                    <h5>{{ product.name }}</h5>
                    <p>{{ product.description }}</p>
                  </div>
                  <div class="clearfix"> </div>
                </td>
                
                <td class="check">
                  <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ item.update_quantity.quantity }}
                    <input type="submit" class="item_add btn btn-outline-dark" value="Update">
                    {% csrf_token %}
                  </form>
                </td>		
                <td>
                  <form action="{% url "cart:cart_remove" product.id %}" method="post">
                    <input type="submit" style="color:red;" class="btn btn-outline-danger to-buy" value="Remove">
                      {% csrf_token %}
                  </form>   
                </td>
                <td>&#x20A6;{{ item.price }}</td>
                <td>&#x20A6;{{ item.total_price }}</td>
              </tr>
            {% endwith %}
          {% endfor %}

          <tr style="text-align:center; background-color:#333; color:gold;">
            <td style="text-align:center; padding:10px; color:#e4e008e1;" class="ring-in">
              <span>Total Amount Of Cart:</span>
              <div class="sed"></div>
              <div class="clearfix"> </div>
            </td>
            <td colspan="3"></td>		
            <td style="text-align:right; color:#e4e008e1;">&#x20A6;{{ cart.get_total_price }}</td>
          </tr>
        </tbody>
      </table>
      <br><hr>
      <p class="text-right">
        <a href="{% url "shop:home" %}"  class=" to-buy btn btn-outline-dark ">Continue shopping</a>
          <a href="{% url "orders:order_create" %}" class="to-buy btn btn-outline-success"> Checkout</a>
        <div class="clearfix"> </div>
      </p>
    </div>
  </div>

{% endblock %}