cart/urls.py
from django.urls import path
from . import views
   
app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:prod_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:prod_id>/', views.cart_remove, name='cart_remove'),

]

s3palace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('search/', views.search, name='search'),
	path('gallery/', views.gallery, name='gallery'),
	path('<int:id>/<slug:slug>/', views.suit_detail,name='suit_detail'),
	path('suits/<slug:category_slug>/', views.category_list,name='product_list_by_category'),
]

shop/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name	
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug]) 


class Suits(models.Model):
    sizes = (
        (40,40),
        (42,42),
        (44,44),
        (46,46),
        (48,48),
        (50,50),
        (52,52),
        (54,54),
        (56,56),
        (58,58),
        (60,60),
        (64,64),
        (66,66),
        (68,68),
        (70,70)
    )
    brands = (
        ('Italian Suits', 'Italian Suits'),
        ('Turkish Suits', 'Turkish Suits'),
        ('Chinese Suits', 'Chinese Suits'),
        ('Italian Shoes', 'Italian Shoes'),
        ('Turkish Shoes', 'Turkish Shoes'),
        ('Chinese Shoes', 'Chinese Shoes')
    )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    category = models.ForeignKey(Category, related_name='suits_products', on_delete=models.CASCADE)
    sizes = models.CharField(max_length=20, blank=True, default='44-60')
    #sizes = models.IntegerField(choices=sizes, null=True, db_index=True, default=40)
    brands = models.CharField(max_length=100, choices=brands, null=True, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
        return reverse('shop:suit_detail', args=[self.id, self.slug])
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    name = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='gallery/%Y/%m/%d',blank=True)
    description = models.CharField(max_length=500, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    product = models.ForeignKey(Suits, on_delete=models.CASCADE, related_name='reviews')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.product}'

    class Meta:
        ordering = ('created',)

shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ('name', 'email', 'body',)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Suits, Category, Gallery, Review
from cart.forms import CartAddProductForm
from django.core.mail import BadHeaderError, send_mail, EmailMessage
from django.db.models import Q 
from cart.cart import Cart
from django.conf import settings
from .forms import ReviewForm

# Create your views here.
def home(request):
	category = None
	categories = Category.objects.all()
	all_suits = Suits.objects.filter(available=True)
	suits = Suits.objects.filter(available=True).order_by('created')[:12]
	last_suit = Suits.objects.filter(available=True).last()
	cart = Cart(request)
	penultimate_suit = Suits.objects.filter(available=True).order_by('-created')[0:1]
	pen_suit = penultimate_suit[0]
                       
	#Category Filters
	chinese_suits = all_suits.filter(category__id__exact=2).order_by('-created')[0:3]
	italian_suits = all_suits.filter(category__id__exact=1).order_by('-created')[0:3]
	turkey_suits = all_suits.filter(category__id__exact=3).order_by('-created')[0:3],

	context = {
		'category': category,
        'last_suit':last_suit,
        'pen_suit':pen_suit,
        'suits':suits,
        'categories': categories,
        'cart': cart,
        'italian_suits':italian_suits,
        'chinese_suits':chinese_suits,
        'turkey_suits':turkey_suits
   		}

	return render(request,'shop/product/index.html', context)


def about(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    cart = Cart(request)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
    
    context = {
		'category': category,
        'suits':suits,
        'cart': cart,
        'categories': categories
     }
    return render(request, 'shop/product/about.html', context)


def gallery(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    gallery = Gallery.objects.all()
    cart = Cart(request)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
    
    context = {
        'category': category,
        'gallery':gallery,
        'cart': cart,
        'suits':suits,
        'categories': categories
     }
    return render(request, 'shop/product/gallery.html', context)


def contact(request):
    cart = Cart(request)
    categories = Category.objects.all()
    context = {'categories':categories, 'cart':cart}
    # Validate contact form 
    if request.method == 'POST':
        # Get details from the form
        fullname = request.POST['fullname']
        print('contact name;', fullname)
        phone_no = request.POST['phonenumber']
        contact_email = request.POST['email']
        message = request.POST['message']
    
        #subject = 'A New Message From SeamlessBuy Store'
        contact_message = f'S3Palace New Message, \n\n' \
                f'Hi! You have a message from {fullname} with details below. \n' \
                f'Phone Number: {phone_no} \n' \
                f'Message: {message}.'

        email_msg = EmailMessage(
            subject="Message From S3Palace", body=contact_message,
            from_email=contact_email,
            to=[settings.EMAIL_HOST_USER],
            headers={'Reply-To': contact_email})
        email_msg.send()
        #messages.success(request, f'Thank you for contacting us! We\'ll get back to you soon.')
        return redirect ('shop:home')
    return render(request, 'shop/product/contact.html', context)


def suit_detail(request, id, slug):
    suit = get_object_or_404(Suits, id=id, slug=slug, available=True)
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    print('This is suit detail=', suit)
    cart = Cart(request)

    # List of active reviews for this post
    reviews = suit.reviews.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            # Create Comment object but don't save to db yet
            new_review = review_form.save(commit=False)
            new_review.product = suit
            new_review.save()
    else:
        review_form = ReviewForm()

    context = {
		'suit': suit,
        'categories':categories,
        'cart':cart,
		'cart_product_form': cart_product_form,
        'review_form':review_form,
        'reviews':reviews
	}
    return render(request,'shop/product/suit_detail.html',context)


def category_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    cart = Cart(request)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
    
    for a in suits:
        print('This is suit:',a, a.get_absolute_url)
        
    context = {
		'category': category,
        'suits':suits,
        'cart':cart,
        'categories': categories
        }
    return render(request,'shop/product/suit_category_list.html', context)

def search(request):
    # get search query
    search_query = request.GET.get('q')
    categories = Category.objects.all()
    cart = Cart(request)
    print('search object: ', search_query)
    suits = Suits.objects.filter(Q(name__icontains=search_query) | Q(category__name__icontains=search_query)).filter(available=True).order_by('created')
    print('returned search results = ', suits)
    context = {'suits':suits, 'search_query':search_query, 'categories':categories, 'cart':cart}

    return render(request, 'shop/product/search_results.html', context)

shop/templates/shop/product/banner.html
{% load static %}
<div class="banner">
	<div class="matter-banner">
	 	<div class="slider">
	    	<div class="callbacks_container">
	      		<ul class="rslides" id="slider">
	        		<li>
	          			<img style="height:100rm;" src="{% static 'images/suit_bg.jpeg' %}" alt="">
						<div class="tes animated wow fadeInUp animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
							<h2>SUITS & SHOES</h2>
							<h3>Quality Italian, Nigerian, Chinese & Turkish Suits</h3>
							<h4>S3 PALACE</h4>
							<h4><i>Your smile &#x263A; is our satisfaction!</i></h4>
						</div>
	       			 </li>
			 		 <li>
	          			<img src="{% static 'images/suit_bg.jpeg' %}" alt=""> 
						<div class="tes animated wow fadeInUp animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
							<h2>SUITS & SHOES</h2>
							<h3>Quality Turkish Suits</h3>
							<h4>S3 PALACE</h4>
							<h4><i>Your smile is our satisfaction!</i></h4>
						</div>					
	       			 </li>
					 <li>
	          			<img src="{% static 'images/suit_bg.jpeg' %}" alt="">
						<div class="tes animated wow fadeInUp animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
							<h2>SUITS & SHOES</h2>
							<h3>Quality Chinese Suits</h3>
							<h4>S3 PALACE</h4>
							<h4><i>Enjoy seamless user experience!</i></h4>
						</div>
	        		</li>	
	      		</ul>
	 	 	</div>
		</div>
	</div>
	<div class="clearfix"> </div>
</div>
<!--//banner-->

shop/templates/shop/product/footer.html
<div class="footer">
	<div class="container">
		<div class="footer-top">
			<div class="col-md-6 top-footer animated wow fadeInLeft" data-wow-delay=".5s">
				<h3>Follow Us On</h3>
				<div class="social-icons">
					<ul class="social">
						<li><a href="https://web.facebook.com/SMILESSUITSANDSHOESPALACE/"><i class="twitter"></i></a> </li>
						<li><a href="https://web.facebook.com/SMILESSUITSANDSHOESPALACE/"><i class="facebook"></i></a></li>	
						<li><a href="https://www.instagram.com/smilessuitsandshoespalace/"><i class="linked"></i> </a></li>						
					</ul>
						<div class="clearfix"></div>
				 </div>
			</div>
			<div class="col-md-6 top-footer1 animated wow fadeInRight" data-wow-delay=".5s">
				<h3>Newsletter</h3>
					<form action="#" method="post">
						{% csrf_token %}
						<input type="text" name="email" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
						<input type="submit" value="SUBSCRIBE">
					</form>
			</div>
			<div class="clearfix"> </div>	
		</div>	
	</div>
{% comment %} Footer Bottom {% endcomment %}
	<div class="footer-bottom">
		<div class="container">
				
				<div class="col-md-4 footer-bottom-cate animated wow fadeInLeft" data-wow-delay=".5s">
					<h6>Quick Links</h6>
					<ul>
						<li><a href="{% url 'shop:home' %}">Home</a></li>
						<li><a href="{% url 'shop:about' %}">About Us</a></li>
						<li><a href="{% url 'shop:about' %}#faq">FAQs</a></li>
						<li><a href="{% url 'shop:gallery' %}">Gallery</a></li>
						{% comment %} <li><a href="#">Sign In</a></li> {% endcomment %}
						<li><a href="{% url 'shop:contact' %}">Contact Us</a></li>
					</ul>
				</div>
				
				<div class="col-md-4 footer-bottom-cate animated wow fadeInRight" data-wow-delay=".5s">
					<h6>Top Brands</h6>
					<ul>
						{% for c in categories %}
						<li {% if category.slug == c.slug %} {% endif %}>
							{% if c.name == 'China' %}
								<a href="{{ c.get_absolute_url }}">{{ c.name }} Suits</a>
							{% elif c.name == 'Italy' %}
								<a href="{{ c.get_absolute_url }}">{{ c.name }} Suits</a>
							{% elif c.name == 'Turkey' %}
								<a href="{{ c.get_absolute_url }}">{{ c.name }} Suits</a>
							{% elif c.name == 'Nigerian' %}
								<a href="{{ c.get_absolute_url }}">{{ c.name }} Suits</a>
							{% endif %}
						</li>
						{% endfor %}
					</ul>
				</div>
				<div class="col-md-4 footer-bottom-cate cate-bottom animated wow fadeInRight" data-wow-delay=".5s">
					<h6>Our Address</h6>
					<ul>
						<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>Adefemi Street, Ushafa, Off Bwari Council Area, <span>Abuja.</span></li>
						<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:support@s3palace.com"></a>support@s3palace.com</li>
						<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>0803 293 0181</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
				<p class="footer-class animated wow fadeInUp animated" data-wow-delay=".5s" 
                style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;"> © 2022 S3Palace . All Rights Reserved </p>
		</div>
	</div>
</div>
<!--footer-->

shop/templates/shop/product/header.html
{% load static %}
<div class="container">
	<div class="head-top">
		<div class="n-avigation">
			<!-- Navbar here -->
			{% include 'shop/product/nav.html' %}
	</div>		
<div class="clearfix"> </div>

shop/templates/shop/product/nav.html
{% load static %}
<nav class="navbar nav_bottom" role="navigation">
				
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header nav_2">
	<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
	<span class="sr-only">Toggle navigation</span>
	<span  style="background-color:#fae103b4" class="icon-bar"></span>
	<span style="background-color:#fae103b4" class="icon-bar"></span>
	<span style="background-color:#fae103b4" class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="#"></a>
</div> 
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
	<ul class="nav navbar-nav nav_1">
		<li><a href="{% url 'shop:home' %}">Home</a></li>
		<li><a href="{% url 'shop:about' %}">About</a></li>
		{% comment %} <li><a href="{% url 'shop:product_list' %}">Products</a></li> {% endcomment %}

		{% comment %} Shoes Category {% endcomment %}
		{% comment %} <li class="dropdown mega-dropdown active">
			<a href="{% url 'shop:home' %}" class="dropdown-toggle" data-toggle="dropdown">Shoes<span class="caret"></span></a>				
			<div class="dropdown-menu mega-dropdown-menu">
				<div class="container-fluid">
					<!-- Tab panes -->
					<div class="tab-content">
						<div class="tab-pane active" id="men">
						<ul class="nav-list list-inline">
							{% for c in categories %}
							<li>
								{% if c.name == 'Italy' %} 
									<a href="{{ c.get_absolute_url }}"><img style="height:100px; width:150px;" src="{% static 'images/italyshoe1.jpeg' %}" class="img-responsive" alt=""/>
										{{c.name}}
									</a>
								{% elif c.name == 'Turkey' %}
									<a href="{{ c.get_absolute_url }}"><img style="height:100px;width:150px;" src="{% static 'images/turkeyshoe1.jpeg' %}" class="img-responsive" alt=""/>
										{{c.name}}
									</a>
								{% elif c.name == 'China' %}
									<a href="{{ c.get_absolute_url }}"><img style="height:100px;width:150px;" src="{% static 'images/chinashoe1.jpeg' %}" class="img-responsive" alt=""/>
										{{c.name}}
									</a>
								{% endif%}
								</li>
							{% endfor %}
						</ul>
						</div>
						
					</div>
				</div>
				<!-- Nav tabs -->
									
			</div>				
		</li> {% endcomment %}

		{% comment %} Suits Category {% endcomment %}
		<li class="dropdown mega-dropdown active">
			<a href="{% url 'shop:home' %}" class="dropdown-toggle" data-toggle="dropdown">Suits<span class="caret"></span></a>				
			<div class="dropdown-menu mega-dropdown-menu">
				<div class="container-fluid">
					<!-- Tab panes -->
					<div class="tab-content">
						<div class="tab-pane active" id="men">
						<ul class="nav-list list-inline" {% if category.slug == c.slug %} {% endif %}>
							{% for c in categories %}
							<li>
								{% if c.name == 'Italy' %} 
									<a href="{{  c.get_absolute_url }}"><img style="height:100px; width:150px;" src="{% static 'images/italysuit1.jpeg' %}" class="img-responsive" alt=""/>
										{{c.name}}
									</a>
								{% elif c.name == 'Turkey' %}
									<a href="{{  c.get_absolute_url }}"><img style="height:100px; width:150px;" src="{% static 'images/turkeysuit1.jpeg' %}" class="img-responsive" alt=""/>
										{{c.name}}
									</a>
								{% elif c.name == 'China' %}
									<a href="{{ c.get_absolute_url }}"><img style="height:100px; width:150px;" src="{% static 'images/chinasuit1.jpeg' %}" class="img-responsive" alt=""/>
										{{c.name}}
									</a>
								{% endif%}
								</li>
							{% endfor %}
						</ul>
						</div>
						
					</div>
				</div>
				<!-- Nav tabs -->
									
			</div>				
		</li>
		<li><a href="{% url 'shop:gallery' %}">Gallery</a></li>
		<li class="last"><a href="{% url 'shop:contact' %}">Contact</a></li>
	</ul>
	</div><!-- /.navbar-collapse -->
</nav>

shop/templates/shop/product/suit_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!--//breadcrumb-->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInLeft;">
			<li><a href="{% url 'shop:home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">{{ suit.category }} Category</li>
			<li class="active">{{ suit.name }}</li>
		</ol>
	</div>
</div>
<!---->

<!--content-->
<div class="products">
	<div class="container">
		<h2>
			{% if category %}{{ category.name }} {% else %}Suit Detail{% endif %}
		</h2>
        <hr>

        {% comment %} Start Row {% endcomment %}
        <div class='row'>
            <div class="col-md-9" style="border: 0px solid red;">
                <div class="content-top1">
                    {% comment %} Product Image {% endcomment %}
                    <div class="col-md-4 col-sm-12" style="width:50%; min-height:700px; border: 0px solid red;">
                        <div class="flexslider">
                            <ul class="slides">
                                <li data-thumb="{{ suit.image.url }}">
                                    <div class="thumb-image"> 
                                        <img style="height:400px; width:100%;" src="{{ suit.image.url }}" data-imagezoom="true" class="img-responsive"> 
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    {% comment %} Product forms {% endcomment %}
                    <div class="col-md-8 col-sm-12" style="min-height:700px; width:50%; border: 0px solid green;">
                        <div class="single-para simpleCart_shelfItem">
                            <h2>{{ suit.name }}</h2>   
                             <div class="star-on">
                                <ul>
                                    <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                                    <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                                    <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                                    <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                                    <li><a href="#"><i class="glyphicon glyphicon-star"> </i></a></li>
                                </ul>
                                {% with reviews.count as total_reviews %}
                
                                <div class="review">
                                    <a href="#" class="text-muted"> {{ total_reviews }} reviews </a>/
                                    <a href="#review">Write a review</a>
                                </div>
                                {% endwith %}

                                <div class="clearfix"> </div>
                            </div>
                            <label  class="add-to item_price">&#x20A6; {{ suit.price }}</label>
                            <br>
                            <div class="col-md-4 top-footer1 animated wow fadeInRight">
                               <form action="{% url "cart:cart_add" suit.id %}" method="post">
                                    	{% csrf_token %} <br>
				       {{ cart_product_form }} <br>
                                    
                                    <input class="item_add btn btn-outline-dark" style="width:100px;" type="submit" value="Add to cart">
                                </form>
                            </div> 
                            <br><br>
                            <div class="available"> 
                                <br><br><hr>
                                <h6 style="text-align:left; color:#e4e008e1;">More Info</h6>
                                <ul>	
                                    <li><b style="color:brown; font-weight: bold;">Size:</b> {{ suit.sizes }}</li> <br>
                                    <li><b style="color:brown; font-weight: bold;">Brand:</b> {{ suit.category }}</li> <br>
                                    <li><b style="color:brown; font-weight: bold;">Availability:</b> {% if suit.available %}In Stock{% else %}Out Of Stock{% endif %}</li> <br>
                                    <li><b style="color:brown; font-weight: bold;">Description:</b> {{ suit.description }}</li>			
                                </ul>
                            </div>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                
                </div>	
            </div> 
            <br>

            {% comment %} Part B {% endcomment %}
            <div class="col-md-3 col-sm-12 mt-10 animated wow fadeInLeft" data-wow-delay=".5s" style="border: 0px solid gold; text-align:center;">
                <!--categories-->
                    <div class="rsidebar span_1_of_left">
                        {% comment %} {% if category %}{{ category.name }}{% else %}Products{% endif %} {% endcomment %}
                            <h3 class="cate">Product Categories</h3>
                            <ul class="menu-drop">
                                <li class="item1"> {% if not category %} {% endif %}
                                    <a href="{% url "shop:home" %}">All Categories</a>
                                    <ul style="text-align:center;" class="cute">
                                        {% for c in categories %}
                                        <li class="subitem1 text-right" {% if category.slug == c.slug %} {% endif %}> 
                                            {% if c.name == 'China' %} 
                                                <a href="{{ c.get_absolute_url }}"> <img style="height:100px;" src="{% static 'images/chinasuit1.jpeg' %}" class="img-responsive" alt=""/>
                                                    {{ c.name }} 
                                            {% elif c.name == 'Italy' %}
                                                <a href="{{ c.get_absolute_url }}"> <img style="height:100px;" src="{% static 'images/italysuit1.jpeg' %}" class="img-responsive" alt=""/>
                                                    {{ c.name }}
                                            {% elif c.name == 'Turkey' %}
                                                    <a href="{{ c.get_absolute_url }}"> <img style="height:100px;" src="{% static 'images/turkeysuit1.jpeg' %}" class="img-responsive" alt=""/>
                                                        {{ c.name }}
                                            {% endif %}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            </ul>
                    </div>

                <!--initiate accordion-->
                        <script type="text/javascript">
                            $(function() {
                                var menu_ul = $('.menu-drop > li > ul'),
                                        menu_a  = $('.menu-drop > li > a');
                                menu_ul.hide();
                                menu_a.click(function(e) {
                                    e.preventDefault();
                                    if(!$(this).hasClass('active')) {
                                        menu_a.removeClass('active');
                                        menu_ul.filter(':visible').slideUp('normal');
                                        $(this).addClass('active').next().stop(true,true).slideDown('normal');
                                    } else {
                                        $(this).removeClass('active');
                                        $(this).next().stop(true,true).slideUp('normal');
                                    }
                                });
                            
                            });
                        </script>
                    <!--//menu-->
            </div>
        </div>
        <hr>
        {% comment %} End of Product Detail {% endcomment %}


        {% comment %} Review Section {% endcomment %}
        <h2>Suit Reviews</h2>
            
        <div id="review" class="row justify-content center">
            <div class="col-md-4 animated wow" style="border:0.5px dashed gold; min-height:200px;">
                {% for review in reviews %}
                    <div  style="background-color: whitesmoke;">
                        {{ review.body }}
                       <small class="text-muted">
                        <i>
                         Review made by: {{ review.name }} on {{ review.created | date:"M d, Y" }}
                        </i>
                        </small>
                       
                     </div>
                {% empty %}
                    <p>There are no reviews yet for this product!</p>
                    <hr> <br>
                {% endfor %}
            </div>
                            
            <!-- Comment Form -->
            <div class="col-md-8 animated wow" style="border:0.5px dashed gold; min-height:200px; margin: auto; text-align:center;">
                    {% if new_review %}       
                        <p>Thanks! Your review has been added.</p>
                    {% else %}
                        <h3>Write a new review</h3> <br>
                        <form method="post">
                           {{ review_form|crispy }}
                           {% csrf_token %}
                           <p><input class="item_add btn btn-outline-warning btn-block btn-sm m-1" type="submit" value="Submit Review"></p>
                        </form> 
                    {% endif %}
            </div>

        </div>


    </div>
</div>



{% endblock content  %}