cart/urls.py
from django.urls import path
from . import views
   
app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:prod_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:prod_id>/', views.cart_remove, name='cart_remove'),

]

s3palace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('search/', views.search, name='search'),
	path('gallery/', views.gallery, name='gallery'),
	path('<int:id>/<slug:slug>/', views.suit_detail,name='suit_detail'),
	path('suits/<slug:category_slug>/', views.category_list,name='product_list_by_category'),
]

shop/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name	
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug]) 


class Suits(models.Model):
    sizes = (
        (40,40),
        (42,42),
        (44,44),
        (46,46),
        (48,48),
        (50,50),
        (52,52),
        (54,54),
        (56,56),
        (58,58),
        (60,60),
        (64,64),
        (66,66),
        (68,68),
        (70,70)
    )
    brands = (
        ('Italian Suits', 'Italian Suits'),
        ('Turkish Suits', 'Turkish Suits'),
        ('Chinese Suits', 'Chinese Suits'),
        ('Italian Shoes', 'Italian Shoes'),
        ('Turkish Shoes', 'Turkish Shoes'),
        ('Chinese Shoes', 'Chinese Shoes')
    )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    category = models.ForeignKey(Category, related_name='suits_products', on_delete=models.CASCADE)
    sizes = models.CharField(max_length=20, blank=True, default='44-60')
    #sizes = models.IntegerField(choices=sizes, null=True, db_index=True, default=40)
    brands = models.CharField(max_length=100, choices=brands, null=True, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
        return reverse('shop:suit_detail', args=[self.id, self.slug])
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    name = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='gallery/%Y/%m/%d',blank=True)
    description = models.CharField(max_length=500, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    product = models.ForeignKey(Suits, on_delete=models.CASCADE, related_name='reviews')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.product}'

    class Meta:
        ordering = ('created',)

shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ('name', 'email', 'body',)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Suits, Category, Gallery, Review
from cart.forms import CartAddProductForm
from django.core.mail import BadHeaderError, send_mail, EmailMessage
from django.db.models import Q 
from cart.cart import Cart
from django.conf import settings
from .forms import ReviewForm

# Create your views here.
def home(request):
	category = None
	categories = Category.objects.all()
	all_suits = Suits.objects.filter(available=True)
	suits = Suits.objects.filter(available=True).order_by('created')[:12]
	last_suit = Suits.objects.filter(available=True).last()
	cart = Cart(request)
	penultimate_suit = Suits.objects.filter(available=True).order_by('-created')[0:1]
	pen_suit = penultimate_suit[0]
                       
	#Category Filters
	chinese_suits = all_suits.filter(category__id__exact=2).order_by('-created')[0:3]
	italian_suits = all_suits.filter(category__id__exact=1).order_by('-created')[0:3]
	turkey_suits = all_suits.filter(category__id__exact=3).order_by('-created')[0:3],

	context = {
		'category': category,
        'last_suit':last_suit,
        'pen_suit':pen_suit,
        'suits':suits,
        'categories': categories,
        'cart': cart,
        'italian_suits':italian_suits,
        'chinese_suits':chinese_suits,
        'turkey_suits':turkey_suits
   		}

	return render(request,'shop/product/index.html', context)


def about(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    cart = Cart(request)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
    
    context = {
		'category': category,
        'suits':suits,
        'cart': cart,
        'categories': categories
     }
    return render(request, 'shop/product/about.html', context)


def gallery(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    gallery = Gallery.objects.all()
    cart = Cart(request)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
    
    context = {
        'category': category,
        'gallery':gallery,
        'cart': cart,
        'suits':suits,
        'categories': categories
     }
    return render(request, 'shop/product/gallery.html', context)


def contact(request):
    cart = Cart(request)
    categories = Category.objects.all()
    context = {'categories':categories, 'cart':cart}
    # Validate contact form 
    if request.method == 'POST':
        # Get details from the form
        fullname = request.POST['fullname']
        print('contact name;', fullname)
        phone_no = request.POST['phonenumber']
        contact_email = request.POST['email']
        message = request.POST['message']
    
        #subject = 'A New Message From SeamlessBuy Store'
        contact_message = f'S3Palace New Message, \n\n' \
                f'Hi! You have a message from {fullname} with details below. \n' \
                f'Phone Number: {phone_no} \n' \
                f'Message: {message}.'

        email_msg = EmailMessage(
            subject="Message From S3Palace", body=contact_message,
            from_email=contact_email,
            to=[settings.EMAIL_HOST_USER],
            headers={'Reply-To': contact_email})
        email_msg.send()
        #messages.success(request, f'Thank you for contacting us! We\'ll get back to you soon.')
        return redirect ('shop:home')
    return render(request, 'shop/product/contact.html', context)


def suit_detail(request, id, slug):
    suit = get_object_or_404(Suits, id=id, slug=slug, available=True)
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    print('This is suit detail=', suit)
    cart = Cart(request)

    # List of active reviews for this post
    reviews = suit.reviews.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            # Create Comment object but don't save to db yet
            new_review = review_form.save(commit=False)
            new_review.product = suit
            new_review.save()
    else:
        review_form = ReviewForm()

    context = {
		'suit': suit,
        'categories':categories,
        'cart':cart,
		'cart_product_form': cart_product_form,
        'review_form':review_form,
        'reviews':reviews
	}
    return render(request,'shop/product/suit_detail.html',context)


def category_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    suits = Suits.objects.filter(available=True)
    cart = Cart(request)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        suits = suits.filter(category=category)
    
    for a in suits:
        print('This is suit:',a, a.get_absolute_url)
        
    context = {
		'category': category,
        'suits':suits,
        'cart':cart,
        'categories': categories
        }
    return render(request,'shop/product/suit_category_list.html', context)

def search(request):
    # get search query
    search_query = request.GET.get('q')
    categories = Category.objects.all()
    cart = Cart(request)
    print('search object: ', search_query)
    suits = Suits.objects.filter(Q(name__icontains=search_query) | Q(category__name__icontains=search_query)).filter(available=True).order_by('created')
    print('returned search results = ', suits)
    context = {'suits':suits, 'search_query':search_query, 'categories':categories, 'cart':cart}

    return render(request, 'shop/product/search_results.html', context)

shop/templates/shop/base.html
{% load static  %}
<!DOCTYPE html>
<html>
<head>
<title></title>
<title>{% block title %}Smiles Suits & Shoes | think satisfaction, think SMILES!{% endblock %}</title>

<link href="{% static 'css/bootstrap-3.1.1.min.css' %}" rel='stylesheet' type='text/css' />

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name='description', content='S3Palace also known as Smiles Suits and Shoes is a Male Clothing Brand that deals on quality and affordable suits and Shoes.
	We pride ourselves in providing quality suits and shoes for you. Your smile is our satisfaction. S3Palace is a place of comfort and luxury. If you are looking for quality suits and shoes at affordable prices, look no further than s3palace.'>
<meta name='Developer', content='Damilare Samuel' />
<meta name="author" content="Sodbridge; Damilare Samuel">
<meta name="keywords" content="Smiles Suits and Shoes Store, S3Palace, S3 palace, affordable suits in Abuja, Italian suits and shoes. Quality shoes in Abuja.
Free delivery of shoes and suits, Suits in Kubwa, Shoes in Kubwa, Ecommerce for shoes and suits" />
 <!-- Icon -->
 <link rel="icon" type="text/css" href="{% static 'images/logo2 copy.png' %}">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>


<link href='//fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>

<!-- start menu -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/simpleCart.min.js' %}"> </script>
<!-- slide -->
<script src="{% static 'js/responsiveslides.min.js' %}"></script>
   <script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: false,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>
  <!-- animation-effect -->
<link href="{% static 'css/animate.min.css' %}" rel="stylesheet"> 
<script src="{% static 'js/wow.min.js' %}"></script>
<script>
 new WOW().init();
</script>
<!-- //animation-effect -->
</head>

<!--header cart-->
<div class="header">
	<div class="header-top">
		<div class="container">
				<div class="col-sm-4 logo animated wow fadeInLeft" data-wow-delay=".5s">
					{% comment %} <img src="{% static 'images/logo2 copy.png' %}" style='height:50px; width:50px;',  alt='S3 Palace logo'/> {% endcomment %}
					<h1><a class='' href="{% url 'shop:home' %}">S3 <span>Palace</span></a></h1>
						
				</div>
			<div class="col-sm-4 world animated wow fadeInRight" data-wow-delay=".5s">
					<div class="cart box_1">
						<a href="{% url 'cart:cart_detail' %}">
						<h3> <div class="total">
							<img src="{% static 'images/cart.png' %}" alt="cart"/></h3>
						</a>
						<p>
              {% with total_items=cart|length %}
                  {% if total_items > 0 %}
                  	Your cart:
                  	<a href="{% url "cart:cart_detail" %}">
                  	{{ total_items }} item{{ total_items|pluralize }},
                  	&#x20A6;{{ cart.get_total_price }}
                  	</a>
                  {% else %}
                  	Your cart is empty.
                  {% endif %}
              {% endwith %} 
						</p>
					</div>
			</div>
			<div class="col-sm-2 number animated wow fadeInRight" data-wow-delay=".5s">
					<span><i class="glyphicon glyphicon-phone"></i>0803 293 0181</span>
					<p>Call me</p>
				</div>
			<div class="col-sm-2 search animated wow fadeInRight" data-wow-delay=".5s">		
				<span id = 'search_bar'><a class="play-icon popup-with-zoom-anim" href="#small-dialog"><i id='btn_search'
				 class="glyphicon glyphicon-search item_add2">
				</i></a></span>
			</div>
				<div class="clearfix"> </div>
		</div>
	</div>
	<!-- Header Cart Ends -->

		<!-- Header Here -->
		{% include 'shop/product/header.html' %}
	
			<!---pop-up-box---->   
					<link href="{% static 'css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all"/>
					<script src="{% static 'js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
					<!---//pop-up-box---->
				<div id="small-dialog" class="mfp-hide">
				<div class="search-top">
						<div class="login">
							<form action="{% url 'shop:search' %}" method="get">
								<!-- {% csrf_token %} -->
								<input type="submit" value="">
								<input type="text" name="q" value="Type something to search..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">		
							
							</form>
						</div>
						<p>	Shopping</p>
					</div>				
				</div>
				 <script>
						$(document).ready(function() {
						$('.popup-with-zoom-anim').magnificPopup({
							type: 'inline',
							fixedContentPos: false,
							fixedBgPos: true,
							overflowY: 'auto',
							closeBtnInside: true,
							preloader: false,
							midClick: true,
							removalDelay: 300,
							mainClass: 'my-mfp-zoom-in'
						});
																						
						});
				</script>			
	<!---->		
		</div>
	</div>
</div>
<body>
{% block content %} {% endblock content  %}
<!-- WhatsApp Contact from WATI -->
<script>
	var url = 'https://wati-integration-service.clare.ai/ShopifyWidget/shopifyWidget.js?62323';
	var s = document.createElement('script');
	s.type = 'text/javascript';
	s.async = true;
	s.src = url;
	var options = {
	"enabled":true,
	"chatButtonSetting":{
	  "backgroundColor":"#4dc247",
	  "ctaText":"",
	  "borderRadius":"25",
	  "marginLeft":"0",
	  "marginBottom":"150",
	  "marginRight":"50",
	  "position":"right"
	},
	"brandSetting":{
	  "brandName":"S3Palace",
	  "brandSubTitle":"Typically replies within 5 mins",
	  // "brandImg":"<img src='{% static 'assets/img/thedietmuse_logo.jpeg' %}' style='height:; width:;'' alt='Logo' class='img-fluid'>",
	  // "brandImg":"https://cdn.clare.ai/wati/images/WATI_logo_square_2.png",
	  "welcomeText":"Hello!\nHow can we help you?",
	  "messageText":"Hello SMILES, I'll love you to take my orders.",
	  "backgroundColor":"#0a5f54",
	  "ctaText":"Start Chat",
	  "borderRadius":"30",
	  "autoShow":false,
	  "phoneNumber":"+2348032930181"
	}
	};
	s.onload = function() {
		CreateWhatsappChatWidget(options);
	};
	var x = document.getElementsByTagName('script')[0];
	x.parentNode.insertBefore(s, x);
</script>
	<!-- END OF WHATSAPP  -->
</body>
<!--footer-->
{% include 'shop/product/footer.html' %}
<!--footer-->
</html>